#Version field no longer needed (deprecated). This compose file will be used with Docker Compose v1.28.4
services:
  portainer:
    image: portainer/portainer
    hostname: portainer
    ports:
      - 9000:9000
    volumes:
      - ./portainer/data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no" # because the exit code(s) are wrong

  influxdb:
    image: influxdb:1.8.4
    hostname: 'influxdb'
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb  
      - ./influxdb/config:/etc/influxdb        
    restart: on-failure
    networks:
      - influx_network

  telegraf:
    image: telegraf:latest
    hostname: 'telegraf'
    volumes:
      - ./telegraf:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock # Mount for Docker API access
    depends_on:
      - influxdb
    networks:
     - influx_network

  kapacitor:
  # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:1.5.8
    hostname: 'kapacitor'
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor  # Mount for kapacitor data directory
      - ./kapacitor/config/:/etc/kapacitor/   # Mount for kapacitor configuration
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
    depends_on:
      - influxdb
    networks:
     - influx_network

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: chronograf:1.8.8
    hostname: 'chronograf'
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/ # Mount for chronograf database
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
    networks:
     - influx_network
      
  grafana:
    image: grafana/grafana
    hostname: 'grafana'
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana
    restart: on-failure
    networks:
      - influx_network
networks:
  influx_network:
    driver: bridge
